In [54]:
import numpy as np
import pandas as pd

In [55]:
appStore = pd.read_csv('./appstore.csv', error_bad_lines=False)

In [56]:
appStore

Date      AppID          AppName Country Version  \
0      2020-07-29 06:53:05  492224193  Сбербанк Онлайн      ru  11.1.0   
1      2020-07-29 06:28:50  492224193  Сбербанк Онлайн      ru  11.1.0   
2      2020-07-29 05:23:33  492224193  Сбербанк Онлайн      ru  11.1.0   
3      2020-07-29 03:06:06  492224193  Сбербанк Онлайн      ru  11.1.0   
4      2020-07-29 01:47:35  492224193  Сбербанк Онлайн      ru  11.1.0   
...                    ...        ...              ...     ...     ...   
11579  2019-06-29 09:44:06  492224193  Сбербанк Онлайн      ru  9.13.1   
11580  2019-06-29 09:38:08  492224193  Сбербанк Онлайн      ru  9.13.1   
11581  2019-06-29 09:04:16  492224193  Сбербанк Онлайн      ru  9.13.1   
11582  2019-06-29 07:18:44  492224193  Сбербанк Онлайн      ru  9.13.1   
11583  2019-06-29 03:48:03  492224193  Сбербанк Онлайн      ru  9.13.1   

               Author  Rating                                 Title  \
0       где кекс ефем       5                       Сбербанк онлайн   
1      Юлия9086428045       3                                     .   
2        Екатерина 79       3  Касательно работы обновлённой версии   
3               !ава!       1                                     .   
4            achjfdhj       1                              ApplePay   
...               ...     ...                                   ...   
11579            Фряз       5                                 Отзыв   
11580         bfdcbut       1                    Не надо усложнять.   
11581      мустафа 76       5                       Вы просто супер   
11582        Regorova       5                   Классное приложение   
11583        uhti5414       5                                   👍👍👍   

                                                  Review  Translated title  \
0      Не скачивается стала обновлять и зависло прило...               NaN   
1      Приложение не открывается после обновления!!!!...               NaN   
2      Добрый день, после последнего обновления пропа...               NaN   
3      Не могу скачать так как требует подключения Wi-fi               NaN   
4      Почему то не могу оплатить при минусе на балан...               NaN   
...                                                  ...               ...   
11579  Благодарю Сбербанк за четкую и оперативную раб...               NaN   
11580  Зачем вы все время усложняете приложение. Выки...               NaN   
11581                                    Вы просто супер               NaN   
11582  Молодцы! Лучшее банковское приложение!\nСделай...               NaN   
11583  Спасибо огромное! Классное приложение, а после...               NaN   

       ...                                    Developer Reply User Tags  \
0      ...                                                NaN  NaN  NaN   
1      ...                                                NaN  NaN  NaN   
2      ...                                                NaN  NaN  NaN   
3      ...                                                NaN  NaN  NaN   
4      ...                                                NaN  NaN  NaN   
...    ...                                                ...  ...  ...   
11579  ...              Спасибо за отзыв! Стараемся для вас 😊  NaN  NaN   
11580  ...  Какие у вас возникли сложности с пополнением б...  NaN  NaN   
11581  ...                                           (づ￣ ³￣)づ  NaN  NaN   
11582  ...  Вы можете создать копилку "Процент от доходов"...  NaN  NaN   
11583  ...                                                NaN  NaN  NaN   

       Categories  Notes  Likes  Dislikes  \
0             NaN    NaN    NaN       NaN   
1             NaN    NaN    NaN       NaN   
2             NaN    NaN    NaN       NaN   
3             NaN    NaN    NaN       NaN   
4             NaN    NaN    NaN       NaN   
...           ...    ...    ...       ...   
11579         NaN    NaN    NaN       NaN   
11580         NaN    NaN    NaN       NaN   
11581         NaN    NaN    NaN      

In [57]:
appStore['Title'].unique()

array(['Сбербанк онлайн', '.', 'Касательно работы обновлённой версии',
       ..., 'Каждый день случайно снимайте денги не знаю',
       'Не надо усложнять.', 'Вы просто супер'], dtype=object)

In [58]:
appStore['Rating'].unique()

array([5, 3, 1, 2, 4], dtype=int64)

In [76]:
appStore['AppName'].unique()

array(['Сбербанк Онлайн'], dtype=object)

In [78]:
appStore['Version'].unique()

array(['11.1.0', '11.0.0', '10.11.1', '10.1.0', '10.15.0', '7.4.4',
       '10.2.1', '10.10.0', '10.9.0', '10.14.0', '10.8.0', '10.13.0',
       '10.12.0', '10.4.1', '8.13.1', '9.9.0', '10.11.0', '10.0.0',
       '10.7.0', '10.6.0', '10.5.0', '10.4.0', '9.7.1', '10.3.0',
       '9.11.0', '10.0.1', '10.2.0', '9.12.0', '8.8.1', '9.5.0', '9.0.0',
       '9.13.1', '8.14.0', '9.1.1'], dtype=object)

In [77]:
appStore['AppID'].unique()

array([492224193], dtype=int64)

In [75]:
appStore['Country'].unique()

array(['ru', 'us', 'tr', 'pt', 'kz', 'kg', 'ua', 'kw', 'by', 'de', 'th',
       'az', 'gb', 'eg', 'it', 'au', 'md', 'pk', 'in', 'lu', 'nz', 'cn',
       'fr', 'ae', 'be', 'hr', 'vn', 'zw', 'nl', 'mn', 'jp', 'ca', 'cy',
       'il', 'uz', 'pl', 'my', 'es'], dtype=object)

In [59]:
appStore['Translated review'].unique()

array([nan])

In [60]:
appStore['Translated title'].unique()

array([nan])

In [61]:
appStore['User'].unique()

array([nan])

In [62]:
appStore['Tags'].unique()

array([nan])

In [63]:
appStore['Categories'].unique()

array([nan])

In [64]:
appStore['Notes'].unique()

array([nan])

In [65]:
appStore['Likes'].unique()

array([nan,  1.,  2.,  3.,  5.,  4.,  8.,  7., 10., 12., 17.])

In [66]:
appStore['Dislikes'].unique()

array([nan,  1.,  2.])

In [67]:
appStore.drop(['Translated review','Translated title', 'User','Tags','Categories','Notes'], axis='columns', inplace=True)

In [80]:
appStore['Likes']=appStore['Likes'].fillna(0)
appStore['Dislikes']=appStore['Likes'].fillna(0)
appStore['Developer Reply']=appStore['Developer Reply'].fillna('')
appStore['Reply Date']=appStore['Reply Date'].fillna('')
appStore['Title']=appStore['Title'].fillna('')
appStore['Review']=appStore['Review'].fillna('')
appStore['Link']=appStore['Link'].fillna('')
appStore['Permalink']=appStore['Permalink'].fillna('')
appStore['AF Link']=appStore['AF Link'].fillna('')
appStore['Date']=appStore['Date'].fillna('')
appStore['Author']=appStore['Author'].fillna('')
appStore['Review']=appStore['Review'].fillna('')


In [81]:
appStore

Date      AppID          AppName Country Version  \
0      2020-07-29 06:53:05  492224193  Сбербанк Онлайн      ru  11.1.0   
1      2020-07-29 06:28:50  492224193  Сбербанк Онлайн      ru  11.1.0   
2      2020-07-29 05:23:33  492224193  Сбербанк Онлайн      ru  11.1.0   
3      2020-07-29 03:06:06  492224193  Сбербанк Онлайн      ru  11.1.0   
4      2020-07-29 01:47:35  492224193  Сбербанк Онлайн      ru  11.1.0   
...                    ...        ...              ...     ...     ...   
11579  2019-06-29 09:44:06  492224193  Сбербанк Онлайн      ru  9.13.1   
11580  2019-06-29 09:38:08  492224193  Сбербанк Онлайн      ru  9.13.1   
11581  2019-06-29 09:04:16  492224193  Сбербанк Онлайн      ru  9.13.1   
11582  2019-06-29 07:18:44  492224193  Сбербанк Онлайн      ru  9.13.1   
11583  2019-06-29 03:48:03  492224193  Сбербанк Онлайн      ru  9.13.1   

               Author  Rating                                 Title  \
0       где кекс ефем       5                       Сбербанк онлайн   
1      Юлия9086428045       3                                     .   
2        Екатерина 79       3  Касательно работы обновлённой версии   
3               !ава!       1                                     .   
4            achjfdhj       1                              ApplePay   
...               ...     ...                                   ...   
11579            Фряз       5                                 Отзыв   
11580         bfdcbut       1                    Не надо усложнять.   
11581      мустафа 76       5                       Вы просто супер   
11582        Regorova       5                   Классное приложение   
11583        uhti5414       5                                   👍👍👍   

                                                  Review           Reply Date  \
0      Не скачивается стала обновлять и зависло прило...                        
1      Приложение не открывается после обновления!!!!...                        
2      Добрый день, после последнего обновления пропа...                        
3      Не могу скачать так как требует подключения Wi-fi                        
4      Почему то не могу оплатить при минусе на балан...                        
...                                                  ...                  ...   
11579  Благодарю Сбербанк за четкую и оперативную раб...  2019-07-02 19:40:32   
11580  Зачем вы все время усложняете приложение. Выки...  2019-06-30 09:07:55   
11581                                    Вы просто супер  2019-07-02 19:41:34   
11582  Молодцы! Лучшее банковское приложение!\nСделай...  2019-07-01 12:25:38   
11583  Спасибо огромное! Классное приложение, а после...                        

                                         Developer Reply  Likes  Dislikes  \
0                                                           0.0       0.0   
1                                                           0.0       0.0   
2                                                           0.0       0.0   
3                                                           0.0       0.0   
4                                                           0.0       0.0   
...                                                  ...    ...       ...   
11579              Спасибо за отзыв! Стараемся для вас 😊    0.0       0.0   
11580  Какие у вас возникли сложности с пополнением б...    0.0       0.0   
11581                                           (づ￣ ³￣)づ    0.0       0.0   
11582  Вы можете создать копилку "Процент от доходов"...    0.0       0.0   
11583                                                       0.0       0.0   

                                                    Link  \
0      https://appstoreconnect.apple.com/WebObjects/i...   
1      https://appstoreconnect.apple.com/WebObjects/i...   
2      https://appstoreconnect.apple.com/WebObjects/i...   
3      https://appstoreconnect.apple.com/WebObjects/i...   
4      https://appstoreconnect.apple.com/WebObjects/i...   
...                   

In [82]:
appStore.to_csv('cleanAppStore.csv', index = False)